#!/usr/bin/env bash

set -euo pipefail

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
repo_root=$(cd -- "$script_dir/.." && pwd)
cd "$repo_root"

mode=${DATE_MODE:-build}
timezone=${DOCUMENT_TIMEZONE:-Europe/Berlin}
generated_file="meta/parameters-date-generated.tex"
use_hardcoded_names=false

locale_available() {
  local target normalized_target

  target=$1
  normalized_target=$(printf '%s' "$target" | tr '[:upper:]' '[:lower:]' | tr -d '-')
  locale -a 2>/dev/null | tr '[:upper:]' '[:lower:]' | tr -d '-' | grep -qx "$normalized_target"
}

case "$mode" in
  manual|build|commit) ;;
  *)
    printf 'ERROR: DATE_MODE must be manual, build, or commit (got %s).\n' "$mode" >&2
    exit 1
    ;;
esac

if [[ "$mode" == "manual" ]]; then
  rm -f "$generated_file"
  printf 'DATE_MODE=manual: No generated metadata file written.\n'
  exit 0
fi

locale_setting=''
if locale_available 'de_DE.UTF-8'; then
  locale_setting='de_DE.UTF-8'
else
  use_hardcoded_names=true
  printf 'WARNING: German locale not available (checked variants of de_DE.UTF-8). Falling back to hardcoded German names.\n' >&2
fi

if date -d '@0' +%s >/dev/null 2>&1; then
  date_style='gnu'
elif date -r 0 +%s >/dev/null 2>&1; then
  date_style='bsd'
else
  printf 'ERROR: Neither GNU date (-d) nor BSD date (-r) is available.\n' >&2
  exit 1
fi

format_date() {
  local format=$1

  if [[ "$date_style" == "gnu" ]]; then
    if [[ -n "$locale_setting" ]]; then
      TZ="$timezone" LC_ALL="$locale_setting" LC_TIME="$locale_setting" date -d "@$epoch" +"$format"
    else
      TZ="$timezone" date -d "@$epoch" +"$format"
    fi
  else
    if [[ -n "$locale_setting" ]]; then
      TZ="$timezone" LC_ALL="$locale_setting" LC_TIME="$locale_setting" date -r "$epoch" +"$format"
    else
      TZ="$timezone" date -r "$epoch" +"$format"
    fi
  fi
}

if [[ "$mode" == "build" ]]; then
  epoch=${SOURCE_DATE_EPOCH:-}
  if [[ -z "$epoch" ]]; then
    epoch=$(date +%s)
  fi
else
  if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    printf 'ERROR: DATE_MODE=commit requires a git repository.\n' >&2
    exit 1
  fi

  epoch=$(git log -1 --format=%ct 2>/dev/null || true)
  if [[ -z "$epoch" ]]; then
    printf 'ERROR: DATE_MODE=commit requires at least one git commit.\n' >&2
    exit 1
  fi
fi

if [[ ! "$epoch" =~ ^[0-9]+$ ]]; then
  printf 'ERROR: Selected timestamp is not a valid epoch value: %s.\n' "$epoch" >&2
  exit 1
fi

day_of_week=$(format_date '%A')
day=$(format_date '%d')
month=$(format_date '%m')
year=$(format_date '%Y')

if [[ "$use_hardcoded_names" == true ]]; then
  weekday_index=$(format_date '%w')
  month_index=$((10#$month))
  weekday_names=(Sonntag Montag Dienstag Mittwoch Donnerstag Freitag Samstag)
  month_names=(Januar Februar März April Mai Juni Juli August September Oktober November Dezember)
  day_of_week=${weekday_names[$weekday_index]}
  month_of_year=${month_names[$((month_index - 1))]}
else
  month_of_year=$(format_date '%B')
fi

cat > "$generated_file" <<EOF
% generated by scripts/generate-date.sh; do not edit manually
\renewcommand{\documentDayOfWeek}{$day_of_week}
\renewcommand{\documentDay}{$day}
\renewcommand{\documentMonth}{$month}
\renewcommand{\documentMonthOfYear}{$month_of_year}
\renewcommand{\documentYear}{$year}
EOF

printf 'Wrote date values to %s (with mode=%s and timezone=%s): %s, %s.%s.%s\n' "$generated_file" "$mode" "$timezone" "$day_of_week" "$day" "$month" "$year"